# Generated by Django 4.1.5 on 2023-07-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_rename_countinstock_product_countinstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/no-image.jpg', null=True, upload_to=''),
        ),
    ]
